# Azure DevOps pipeline file for deploying a React.js application to an Azure Blob static website
# Replace <YOUR_STORAGE_ACCOUNT_NAME> with the name of your storage account
# Replace <YOUR_CONTAINER_NAME> with the name of your blob container

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

- task: AzureBlobFileCopy@4
  inputs:
    SourcePath: '$(Build.SourcesDirectory)/build'
    azureSubscription: '0c4bb8f8-40ca-43b1-b3a9-a059d5fc794f'
    DestinationContainerName: '$web'
    storage: 'sampleazurestatichost.blob.core.windows.net'
    BlobPrefix: '$(Build.BuildId)/'
    outputStorageUri: 'blobStorageUri'
  displayName: 'Copy files to Azure Blob storage'

- task: AzureCLI@2
  inputs:
    azureSubscription: '0c4bb8f8-40ca-43b1-b3a9-a059d5fc794f'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az storage blob service-properties update --account-name <YOUR_STORAGE_ACCOUNT_NAME> --static-website --404-document 404.html --index-document index.html
    failOnStandardError: true
  displayName: 'Configure static website'

- task: AzureCLI@2
  inputs:
    azureSubscription: '<YOUR_AZURE_SUBSCRIPTION>'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az storage blob update-batch --account-name sampleazurestatichost --source $(blobStorageUri) --pattern $(Build.BuildId)/* --destination '$web'
    failOnStandardError: true
  displayName: 'Deploy to Azure Blob storage'
